### ISSUE TITLE
[ Init ] GlobalStyle, theme 적용

### ISSUE THREAD

**Issue by thisishwarang** [NOWSOPT-CDSP-WEB-7/YES24-WEB-CLIENT#2]
## 🛠 Issue

- GlobalStyle, styled-reset적용
- theme.ts 파일 생성 및 작성

## 📝 To-do

- [x] GlobalStyle 파일 생성 및 작성
- [x] styled-reset 적용
- [x] theme 파일 생성 및 작성
