### ISSUE TITLE
[ Feat ] 실시간 티켓 랭킹 컴포넌트 구현

### ISSUE THREAD

**Issue by ocahs9** [NOWSOPT-CDSP-WEB-7/YES24-WEB-CLIENT#29]
## 🛠 Issue

- 슬라이드 오른쪽에 흰 공백 있는 이슈 : slidesOffsetAfter={-150} 로 해결

## 📝 To-do

- [x] 티켓 랭킹 헤더 구현
- [x] 티켓 랭킹 캐러셀 구현
- [x] 티켓 랭킹 하단 '랭킹 더보기' 버튼 구현
