### ISSUE TITLE
[ Init ] eslint & prettier 적용

### ISSUE THREAD

**Issue by ocahs9** [NOWSOPT-CDSP-WEB-7/YES24-WEB-CLIENT#4]
## 🛠 Issue

- 코드 문법 검사, 포맷팅을 위해 eslint와 prettier를 설치하고 초기 세팅합니다.

## 📝 To-do

- [x] eslint 설치
- [x] prettier 설치
- [x] eslint 초기 세팅 (옵션 설정)
- [x] prettier 초기 세팅 (옵션 설정)
- [x] eslint와 prettier 충돌 방지
