### ISSUE TITLE
[ Feat ] 모달 구현

### ISSUE THREAD

**Issue by ocahs9** [NOWSOPT-CDSP-WEB-7/YES24-WEB-CLIENT#42]
## 🛠 Issue

- 백드롭이 뭔지 모르니까 찾아보자~
- backdrop 쓰려다가 오래 걸렸습니다.

## 📝 To-do

- [x] 모달 구현
- [x] 모달 위치 조정, 백드롭 투명도 조정
- [x] 모달 켜져있을 때 스크롤 방지(그러나, 뒤의 화면은 자동 움직임은 유지)
- [x] 모달 잘 꺼지고 켜지도록 만들기
